######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 15:02:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . 
QT += network
CONFIG += crypto


# Input
HEADERS += main.hh neighbors.hh router.hh helper.hh files.hh
SOURCES += main.cc neighbors.cc router.cc helper.cc files.cc
